#!/bin/sh
echo "prepare to install prerequisite packages..."
#sudo apt-get install bison libasound2-dev swig python-dev mplayer flac libsndfile1-dev libflac++-dev

sudo cp -rf deps/libmsc.so /usr/lib/
